name: Launch_me
on:
  pull_request:
    branches:
      - "main"
jobs:
  main:
    runs-on: ubuntu-latest
    name: Expose info further
    steps:
      - name: Test
        run: echo ${{ github.ref_name }}
