name: Launch_me
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  main:
    runs-on: ubuntu-latest
    name: Expose info
    steps:
      - name: Test
        run: echo {{ github.ref_name }}
